EDA

In [5]:
import pandas as pd 
import sqlite3

In [6]:
conn= sqlite3.connect('sales_analysis.db')

In [7]:
tables=pd.read_sql_query("select name from sqlite_master where type='table'",conn)
tables

            name
0      Customers
1     OrderItems
2         Orders
3       Payments
4  sales_summary
5    sales_table
6   sales_table1
7       Products

In [8]:
for table in tables ['name']:
    print(f'{table}')
    print('count of records',pd.read_sql(f"select count(*) as count from {table}",conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5",conn))

Customers
count of records 89316

    customer_id  customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                     58125     varzea paulista             SP
1  PxA7fv9spyhx                      3112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                      4119             jandira             SP
3  EOEsCQ6QlpIg                     18212          uberlandia             MG
4  mVz5LO2Vd6cL                     88868            ilhabela             SP

OrderItems
count of records 89316

       order_id    product_id     seller_id   price  shipping_charges    cost
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65  308.16
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79  194.59
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38   81.78
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72  295.22
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66  810.56

Orders
count of records 89316

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18

Payments
count of records 89316

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,Axfy13Hk4PIk,1,credit_card,1,259.14
1,v6px92oS8cLG,1,credit_card,8,382.39
2,Ulpf9skrhjfm,1,credit_card,4,249.25
3,bwJVWupf2keN,1,credit_card,2,27.79
4,Dd0QnrMk9Cj5,1,credit_card,1,76.15

sales_summary
count of records 28607

,city,order_status,order_date,product_id,seller_id,total_cost,payment_type,total_sales,product_category_name
0,guariba,delivered,2018-01-04 22:20:44,00BIIFInAdcQ,va3iGyjj4VVz,60.81,credit_card,184.26,health_beauty
1,machado,delivered,2017-08-15 00:14:11,00FVdl7l7TLz,bI5cDrYjs9Qa,487.32,voucher,87.10,toys
2,irati,delivered,2018-07-15 12:29:19,00MeCa7ZMo03,6RBm8XoBSX9U,444.26,credit_card,358.34,toys
3,itauna,delivered,2018-05-10 20:42:12,00V9K0LkMBYL,WTbhLip6Y9IF,606.78,credit_card,136.42,toys
4,aparecida,delivered,2018-01-16 12:40:56,00ehq6lzh6MX,w44b3CnkAU44,4442.88,credit_card,1929.84,auto

sales_table
count of records 28607

,city,state,order_status,order_date,product_id,seller_id,total_cost,payment_type,total_sales,product_category_name
0,guariba,SP,delivered,2018-01-04 22:20:44,00BIIFInAdcQ,va3iGyjj4VVz,60.81,credit_card,184.26,health_beauty
1,machado,MG,delivered,2017-08-15 00:14:11,00FVdl7l7TLz,bI5cDrYjs9Qa,487.32,voucher,87.10,toys
2,irati,PR,delivered,2018-07-15 12:29:19,00MeCa7ZMo03,6RBm8XoBSX9U,444.26,credit_card,358.34,toys
3,itauna,MG,delivered,2018-05-10 20:42:12,00V9K0LkMBYL,WTbhLip6Y9IF,606.78,credit_card,136.42,toys
4,aparecida,ES,delivered,2018-01-16 12:40:56,00ehq6lzh6MX,w44b3CnkAU44,4442.88,credit_card,1929.84,auto

sales_table1
count of records 28607

,city,state,order_status,order_date,product_id,seller_id,total_cost,payment_type,total_sales,product_category_name,profit,profit_margin
0,guariba,SP,delivered,2018-01-04 22:20:44,00BIIFInAdcQ,va3iGyjj4VVz,60.81,credit_card,184.26,health_beauty,123.45,66.997721
1,machado,MG,delivered,2017-08-15 00:14:11,00FVdl7l7TLz,bI5cDrYjs9Qa,487.32,voucher,87.10,toys,-400.22,-459.494834
2,irati,PR,delivered,2018-07-15 12:29:19,00MeCa7ZMo03,6RBm8XoBSX9U,444.26,credit_card,358.34,toys,-85.92,-23.977228
3,itauna,MG,delivered,2018-05-10 20:42:12,00V9K0LkMBYL,WTbhLip6Y9IF,606.78,credit_card,136.42,toys,-470.36,-344.788154
4,aparecida,ES,delivered,2018-01-16 12:40:56,00ehq6lzh6MX,w44b3CnkAU44,4442.88,credit_card,1929.84,auto,-2513.04,-130.220122

Products
count of records 27451

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,90K0C1fIyQUf,toys,491.0,19.0,12.0,16.0
1,qejhpMGGVcsl,watches_gifts,440.0,18.0,14.0,17.0
2,qUS5d2pEAyxJ,costruction_tools_garden,2200.0,16.0,16.0,16.0
3,639iGvMyv0De,toys,1450.0,68.0,3.0,48.0
4,1lycYGcsic2F,toys,300.0,17.0,4.0,12.0

In [9]:

Payments=pd.read_sql_query("select * from Payments",conn)

In [10]:
Payments.shape

(89316, 5)

In [11]:
Payments['order_id'].nunique()

89316

In [12]:
Orders=pd.read_sql_query("select * from Orders",conn)

In [13]:
Orders['customer_id'].nunique()

89316

In [14]:
Customers=pd.read_sql_query("select * from Customers",conn)
Customers['customer_city'].nunique()

3735

In [15]:
Customers.groupby(['customer_city','customer_state'])[['customer_id']].count()

                                    customer_id
customer_city       customer_state
abadia dos dourados MG                        2
abaete              MG                       10
abaetetuba          PA                       12
abaira              BA                        1
abare               BA                        2
...                                         ...
xexeu               PE                        1
xinguara            PA                        7
zacarias            SP                        2
ze doca             MA                        4
zortea              SC                        1

[3886 rows x 1 columns]

In [16]:
OrderItems=pd.read_sql_query("select * from OrderItems",conn)
OrderItems.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges',
       'cost'],
      dtype='object')

In [17]:
OrderItems['cost']=OrderItems['price']+OrderItems['shipping_charges']

In [18]:
OrderItems.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges',
       'cost'],
      dtype='object')

In [19]:
table_name='OrderItems'
display(pd.read_sql(f"select * from {table_name} limit 5",conn))

       order_id    product_id     seller_id   price  shipping_charges    cost
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65  308.16
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79  194.59
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38   81.78
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72  295.22
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66  810.56

In [20]:
display(OrderItems.head())

       order_id    product_id     seller_id   price  shipping_charges    cost
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65  308.16
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79  194.59
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38   81.78
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72  295.22
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66  810.56

In [21]:
table_name='OrderItems'
display(pd.read_sql(f"select * from {table_name} limit 5",conn))

       order_id    product_id     seller_id   price  shipping_charges    cost
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65  308.16
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79  194.59
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38   81.78
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72  295.22
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66  810.56

In [22]:
Products=pd.read_sql_query("select * from Products",conn)
duplicates= Products[Products.duplicated(keep=False)]
print(duplicates)
Products_clean=Products.drop_duplicates(keep='first')
Products_clean.to_sql('Products',conn,index=False,if_exists='replace')

Empty DataFrame
Columns: [product_id, product_category_name, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []

27451

In [23]:
OrderItems=pd.read_sql_query("select * from OrderItems",conn)

In [24]:
OrderItems.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges',
       'cost'],
      dtype='object')

In [25]:
index_commands=[
    "CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON Orders(customer_id);",
    "CREATE INDEX IF NOT EXISTS idx_orderitems_order_id ON OrderItems(order_id);",
    "CREATE INDEX IF NOT EXISTS idx_orderitems_product_id ON OrderItems(product_id);",
    "CREATE INDEX IF NOT EXISTS idx_payments_order_id ON Payments(order_id);",
    "CREATE INDEX IF NOT EXISTS idx_products_product_id ON Products(product_id);"
]

try:
    cursor=conn.cursor()
    for command in index_commands:
        cursor.execute(command)
    conn.commit()
    print("indexes created succesfully")
except Exception as e:
    print(f"error during index creation: {e}")

full_query = """
SELECT
    C.customer_city AS city,
    C.customer_state AS state,
    O.order_status AS order_status,
    O.order_purchase_timestamp AS order_date,
    OI.order_id,
    OI.product_id,
    OI.seller_id,
    OI.item_price,
    OI.shipping_charges,
    OI.item_revenue,
    P.payment_type,
    PR.product_category_name
FROM Orders O
JOIN Customers C
    ON O.customer_id = C.customer_id
JOIN (
    SELECT
        order_id,
        product_id,
        seller_id,
        SUM(price) AS item_price,
        SUM(shipping_charges) AS shipping_charges,
        SUM(price + shipping_charges) AS item_revenue
    FROM OrderItems
    GROUP BY order_id, product_id, seller_id
) OI
    ON O.order_id = OI.order_id
LEFT JOIN (
    SELECT
        order_id,
        MIN(payment_type) AS payment_type
    FROM Payments
    GROUP BY order_id
) P
    ON O.order_id = P.order_id
LEFT JOIN Products PR
    ON OI.product_id = PR.product_id;
"""

indexes created succesfully

In [26]:
import time
start=time.time()
new_table=pd.read_sql_query(full_query,conn)
end=time.time()
print(f"query executed in:{(end-start)/60} minutes")

query executed in:0.7171882549921672 minutes

In [27]:
print("Shape:", new_table.shape)
print("\nColumns:")
print(new_table.columns.tolist())

display(new_table.head())

Shape: (89316, 12)

Columns:
['city', 'state', 'order_status', 'order_date', 'order_id', 'product_id', 'seller_id', 'item_price', 'shipping_charges', 'item_revenue', 'payment_type', 'product_category_name']

,city,state,order_status,order_date,order_id,product_id,seller_id,item_price,shipping_charges,item_revenue,payment_type,product_category_name
0,varzea paulista,SP,delivered,2017-10-22 18:57:54,Axfy13Hk4PIk,90K0C1fIyQUf,ZWM05J9LcBSF,223.51,84.65,308.16,credit_card,toys
1,armacao dos buzios,RJ,delivered,2018-06-20 21:40:31,v6px92oS8cLG,qejhpMGGVcsl,IjlpYfhUbRQs,170.80,23.79,194.59,credit_card,watches_gifts
2,jandira,SP,delivered,2018-02-16 16:19:31,Ulpf9skrhjfm,qUS5d2pEAyxJ,77p2EYxcM9MD,64.40,17.38,81.78,credit_card,costruction_tools_garden
3,uberlandia,MG,delivered,2018-08-18 18:04:29,bwJVWupf2keN,639iGvMyv0De,jWzS0ayv9TGf,264.50,30.72,295.22,credit_card,toys
4,ilhabela,SP,delivered,2017-12-22 16:44:04,Dd0QnrMk9Cj5,1lycYGcsic2F,l1pYW6GBnPMr,779.90,30.66,810.56,credit_card,toys

In [28]:

print("Dataset shape:", new_table.shape)

print("\nDuplicate rows:", new_table.duplicated().sum())

print("\nMissing values:")
print(new_table.isnull().sum())

print("\nUnique orders:", new_table["order_id"].nunique())

print("\nUnique products:", new_table["product_id"].nunique())

print("\nRevenue totals:")
print("Item price:", round(new_table["item_price"].sum(), 2))
print("Shipping charges:", round(new_table["shipping_charges"].sum(), 2))
print("Item revenue:", round(new_table["item_revenue"].sum(), 2))

Dataset shape: (89316, 12)

Duplicate rows: 0

Missing values:
city                       0
state                      0
order_status               0
order_date                 0
order_id                   0
product_id                 0
seller_id                  0
item_price                 0
shipping_charges           0
item_revenue               0
payment_type               0
product_category_name    308
dtype: int64

Unique orders: 89316

Unique products: 27451

Revenue totals:
Item price: 30447872.89
Shipping charges: 3955199.17
Item revenue: 34403072.06

In [29]:
print("Item price nulls:", new_table["item_price"].isnull().sum())
print("Shipping charges nulls:", new_table["shipping_charges"].isnull().sum())
print("Item revenue nulls:", new_table["item_revenue"].isnull().sum())

print(
    "Revenue calculation mismatches:",
    (
        (new_table["item_price"] + new_table["shipping_charges"])
        != new_table["item_revenue"]
    ).sum()
)

payment_counts = (
    new_table.groupby("order_id")["payment_type"]
    .nunique()
)

print("\nOrders with multiple payment types:", (payment_counts > 1).sum())
print("Orders with one payment type:", (payment_counts == 1).sum())

Item price nulls: 0
Shipping charges nulls: 0
Item revenue nulls: 0
Revenue calculation mismatches: 0

Orders with multiple payment types: 0
Orders with one payment type: 89316

In [30]:
missing_category = new_table[
    new_table["product_category_name"].isnull()
]

print("Rows with missing categories:", len(missing_category))

print(
    "Unique products with missing categories:",
    missing_category["product_id"].nunique()
)

print("\nSample missing-category products:")
print(
    missing_category[
        ["product_id", "city", "state", "item_price", "item_revenue"]
    ].head(10)
)

print(
    "\nAre these product IDs present in Products?",
    missing_category["product_id"].isin(
        pd.read_sql_query("SELECT product_id FROM Products", conn)["product_id"]
    ).all()
)

Rows with missing categories: 308
Unique products with missing categories: 141

Sample missing-category products:
        product_id                     city state  item_price  item_revenue
329   6cDVtksZH7KU              turvelandia    GO       29.40         76.95
1037  z6g5uM3fiCVO                ji-parana    RO       18.99         42.60
1179  N6XMQZiwCJ3t                 mesquita    RJ      509.99        557.54
1589  W3IIy0dnIfkU     sao jose dos pinhais    PR      432.90        439.77
3061  Z2X9RgoeYqaj    campina grande do sul    PR       45.53        119.09
3210  CLZ9JZqycnNT  espirito santo do turvo    SP      261.00        394.85
3632  x6gerAoELDdu        sao jose da barra    MG      399.20        446.75
3752  sNtRBW3JfRjj                sao paulo    SP      126.69        188.01
3825  OyECAoOQX8Ah                  ubatuba    SP       74.89        105.28
4444  PP5cKHUvzDD5                     tupa    SP      509.99        540.65

Are these product IDs present in Products? True

In [31]:
missing_product_ids = missing_category["product_id"].unique().tolist()

placeholders = ",".join(["?"] * len(missing_product_ids))

category_check = pd.read_sql_query(
    f"""
    SELECT product_id, product_category_name
    FROM Products
    WHERE product_id IN ({placeholders})
    """,
    conn,
    params=missing_product_ids
)

print("Matching product records:", len(category_check))
print("\nCategory value counts:")
print(
    category_check["product_category_name"]
    .fillna("<NULL>")
    .value_counts(dropna=False)
)

print("\nSample source records:")
print(category_check.head(15))

Matching product records: 141

Category value counts:
product_category_name
<NULL>    141
Name: count, dtype: int64

Sample source records:
      product_id product_category_name
0   0RgDnQKQBQXX                  None
1   0mQyiS0fieDG                  None
2   28XCimIEK8Ks                  None
3   2ChyLq09YEmq                  None
4   2dr513rtDZw3                  None
5   2wAGSCJPFeKE                  None
6   34gRYtryKmFg                  None
7   4EJ4bFIK6Xep                  None
8   4JOmYX7sWpjP                  None
9   4miksVAdb9jT                  None
10  5UPKeUyFqCTY                  None
11  5gjt2T2OSHe3                  None
12  6cDVtksZH7KU                  None
13  6q5hrm2Sm8bM                  None
14  7K2Llqz5zqYr                  None

In [32]:
sales_clean = new_table.copy()

sales_clean["product_category_name"] = (
    sales_clean["product_category_name"]
    .fillna("Unknown")
)

print("Original rows:", len(new_table))
print("Cleaned rows:", len(sales_clean))

print(
    "\nMissing categories after cleaning:",
    sales_clean["product_category_name"].isnull().sum()
)

print("\nCategory distribution:")
print(
    sales_clean["product_category_name"]
    .value_counts()
    .head(10)
)

print(
    "\nUnknown category rows:",
    (sales_clean["product_category_name"] == "Unknown").sum()
)

Original rows: 89316
Cleaned rows: 89316

Missing categories after cleaning: 0

Category distribution:
product_category_name
toys                     67027
health_beauty             2351
bed_bath_table            2146
sports_leisure            1837
furniture_decor           1760
computers_accessories     1715
housewares                1340
watches_gifts             1196
telephony                  912
auto                       829
Name: count, dtype: int64

Unknown category rows: 308

In [33]:
explain_query=f"EXPLAIN {full_query}"
explain_result=pd.read_sql_query(explain_query,conn)
print(explain_result)

     addr         opcode  p1   p2  p3          p4  p5 comment
0       0           Init   0  189   0        None   0    None
1       1  InitCoroutine   1   67   2        None   0    None
2       2     SorterOpen   7    5   0  k(3,B,B,B)   0    None
3       3        Integer   0    3   0        None   0    None
4       4           Null   0    6   8        None   0    None
..    ...            ...  ..  ...  ..         ...  ..     ...
186   186           Next  12  118   1        None   0    None
187   187           Next   1  115   0        None   1    None
188   188           Halt   0    0   0        None   0    None
189   189    Transaction   0    0  39           0   1    None
190   190           Goto   0    1   0        None   0    None

[191 rows x 8 columns]

In [24]:
import time
import sqlite3  # Assuming you're using SQLite

try:
    print("Starting query execution...")
    start = time.time()
    
    # Set a timeout if using SQLite (adjust the seconds as needed)
    conn.execute("PRAGMA timeout = 300000;")  # 5 minutes in milliseconds
    
    # Execute the query
    new_table = pd.read_sql_query(full_query, conn)
    
    end = time.time()
    print(f"Query executed in: {(end-start)/60} minutes")
    print(f"Result shape: {new_table.shape}")
    print(f"First few rows: {new_table.head()}")
except Exception as e:
    print(f"Error executing query: {e}")
    
    # If using SQLite, you can check if it's a timeout
    if isinstance(e, sqlite3.OperationalError) and "timeout" in str(e).lower():
        print("The query timed out. Consider optimizing your query or increasing the timeout.")

Starting query execution...
Query executed in: 0.16872771978378295 minutes
Result shape: (28607, 10)
First few rows:         city state order_status           order_date    product_id  \
0    guariba    SP    delivered  2018-01-04 22:20:44  00BIIFInAdcQ
1    machado    MG    delivered  2017-08-15 00:14:11  00FVdl7l7TLz
2      irati    PR    delivered  2018-07-15 12:29:19  00MeCa7ZMo03
3     itauna    MG    delivered  2018-05-10 20:42:12  00V9K0LkMBYL
4  aparecida    ES    delivered  2018-01-16 12:40:56  00ehq6lzh6MX

      seller_id  total_cost payment_type  total_sales product_category_name
0  va3iGyjj4VVz       60.81  credit_card       184.26         health_beauty
1  bI5cDrYjs9Qa      487.32      voucher        87.10                  toys
2  6RBm8XoBSX9U      444.26  credit_card       358.34                  toys
3  WTbhLip6Y9IF      606.78  credit_card       136.42                  toys
4  w44b3CnkAU44     4442.88  credit_card      1929.84                  auto

In [34]:
new_table.head()

,city,state,order_status,order_date,order_id,product_id,seller_id,item_price,shipping_charges,item_revenue,payment_type,product_category_name
0,varzea paulista,SP,delivered,2017-10-22 18:57:54,Axfy13Hk4PIk,90K0C1fIyQUf,ZWM05J9LcBSF,223.51,84.65,308.16,credit_card,toys
1,armacao dos buzios,RJ,delivered,2018-06-20 21:40:31,v6px92oS8cLG,qejhpMGGVcsl,IjlpYfhUbRQs,170.80,23.79,194.59,credit_card,watches_gifts
2,jandira,SP,delivered,2018-02-16 16:19:31,Ulpf9skrhjfm,qUS5d2pEAyxJ,77p2EYxcM9MD,64.40,17.38,81.78,credit_card,costruction_tools_garden
3,uberlandia,MG,delivered,2018-08-18 18:04:29,bwJVWupf2keN,639iGvMyv0De,jWzS0ayv9TGf,264.50,30.72,295.22,credit_card,toys
4,ilhabela,SP,delivered,2017-12-22 16:44:04,Dd0QnrMk9Cj5,1lycYGcsic2F,l1pYW6GBnPMr,779.90,30.66,810.56,credit_card,toys

In [35]:
new_table['product_id'].nunique()

27451

In [36]:
new_table.shape

(89316, 12)

In [38]:
new_table['order_status'].nunique()

7

In [40]:
new_table.duplicated().sum()

np.int64(0)

In [42]:
new_table.isnull().sum()

city                       0
state                      0
order_status               0
order_date                 0
order_id                   0
product_id                 0
seller_id                  0
item_price                 0
shipping_charges           0
item_revenue               0
payment_type               0
product_category_name    308
dtype: int64

In [43]:
new_table.dtypes

city                      object
state                     object
order_status              object
order_date                object
order_id                  object
product_id                object
seller_id                 object
item_price               float64
shipping_charges         float64
item_revenue             float64
payment_type              object
product_category_name     object
dtype: object

In [44]:
new_table['city'].unique()

array(['varzea paulista', 'armacao dos buzios', 'jandira', ...,
       'nossa senhora das dores', 'barra longa', 'macuco de minas'],
      shape=(3735,), dtype=object)

In [45]:
new_table['state'].unique()

array(['SP', 'RJ', 'MG', 'SC', 'ES', 'RN', 'BA', 'DF', 'RS', 'PE', 'GO',
       'CE', 'PR', 'MA', 'PI', 'MT', 'MS', 'SE', 'RO', 'TO', 'AM', 'AP',
       'PB', 'PA', 'AL', 'AC', 'RR'], dtype=object)

In [46]:
new_table['product_id'].unique()

array(['90K0C1fIyQUf', 'qejhpMGGVcsl', 'qUS5d2pEAyxJ', ...,
       'w2OtdEjwNHBr', 'W8vikEizUggJ', '5pbzE0rDy61l'],
      shape=(27451,), dtype=object)

In [47]:
new_table['seller_id'].unique()

array(['ZWM05J9LcBSF', 'IjlpYfhUbRQs', '77p2EYxcM9MD', ...,
       'K6yDyz4ENZbi', 'IogS1BthBTFq', 'NLudVw0fmtlb'],
      shape=(2929,), dtype=object)

In [48]:
new_table['product_category_name'].unique()

array(['toys', 'watches_gifts', 'costruction_tools_garden',
       'bed_bath_table', 'auto', 'health_beauty', 'cool_stuff',
       'garden_tools', 'furniture_decor', 'fashion_shoes',
       'sports_leisure', 'baby', 'housewares',
       'construction_tools_construction', 'electronics',
       'home_appliances', 'audio', 'consoles_games', 'stationery',
       'furniture_living_room', 'computers_accessories', 'perfumery',
       'kitchen_dining_laundry_garden_furniture',
       'fashion_bags_accessories', 'market_place', 'telephony',
       'home_construction', None, 'office_furniture',
       'industry_commerce_and_business', 'food_drink', 'drinks',
       'agro_industry_and_commerce', 'signaling_and_security', 'food',
       'pet_shop', 'luggage_accessories', 'home_appliances_2',
       'small_appliances', 'tablets_printing_image',
       'construction_tools_lights', 'musical_instruments', 'home_confort',
       'air_conditioning', 'construction_tools_safety',
       'costruction_tools_tools', 'books_technical',
       'books_general_interest', 'books_imported', 'computers',
       'cine_photo', 'music', 'fashion_male_clothing', 'fashion_sport',
       'fixed_telephony', 'fashion_underwear_beach', 'furniture_bedroom',
       'art', 'christmas_supplies', 'dvds_blu_ray', 'flowers',
       'la_cuisine', 'furniture_mattress_and_upholstery',
       'small_appliances_home_oven_and_coffee', 'home_comfort_2',
       'arts_and_craftmanship', 'party_supplies',
       'fashion_childrens_clothes', 'fashio_female_clothing',
       'security_and_services', 'diapers_and_hygiene'], dtype=object)

In [50]:
new_table['payment_type'].unique()

array(['credit_card', 'wallet', 'voucher', 'debit_card'], dtype=object)

In [52]:
cursor =conn.cursor()

In [53]:
print("Data types:")
print(sales_clean.dtypes)

print("\nDate range:")
sales_clean["order_date"] = pd.to_datetime(
    sales_clean["order_date"], errors="coerce"
)
print("Start:", sales_clean["order_date"].min())
print("End:", sales_clean["order_date"].max())
print("Invalid dates:", sales_clean["order_date"].isna().sum())

print("\nNumeric summary:")
print(
    sales_clean[
        ["item_price", "shipping_charges", "item_revenue"]
    ].describe().round(2)
)

Data types:
city                      object
state                     object
order_status              object
order_date                object
order_id                  object
product_id                object
seller_id                 object
item_price               float64
shipping_charges         float64
item_revenue             float64
payment_type              object
product_category_name     object
dtype: object

Date range:
Start: 2016-09-04 21:15:19
End: 2018-09-03 09:06:57
Invalid dates: 0

Numeric summary:
       item_price  shipping_charges  item_revenue
count    89316.00          89316.00      89316.00
mean       340.90             44.28        385.18
std        557.46             37.67        558.49
min          0.85              0.00          1.14
25%         59.65             20.11        107.71
50%        136.90             35.06        184.65
75%        399.20             57.19        437.86
max       6735.00            409.68       6738.82

In [54]:

import os

# Final validation
print("Rows:", len(sales_clean))
print("Columns:", len(sales_clean.columns))
print("Duplicate rows:", sales_clean.duplicated().sum())
print("Missing values:", sales_clean.isnull().sum().sum())

# Verify revenue calculation
revenue_mismatches = (
    sales_clean["item_price"] + sales_clean["shipping_charges"]
    != sales_clean["item_revenue"]
).sum()

print("Revenue mismatches:", revenue_mismatches)

# Export final dataset
output_file = os.path.abspath("sales_master_data_cleaned.csv")
sales_clean.to_csv(output_file, index=False)

print("\nFinal dataset exported to:")
print(output_file)
print("Export complete.")

Rows: 89316
Columns: 12
Duplicate rows: 0
Missing values: 0
Revenue mismatches: 0

Final dataset exported to:
C:\Users\rohit\sales_master_data_cleaned.csv
Export complete.

In [1]:
import os

print("Current working directory:", os.getcwd())
print("Database file exists:", os.path.exists("sales_analysis.db"))

Current working directory: C:\Users\rohit
Database file exists: True

In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("sales_analysis.db")

tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name",
    conn
)

display(tables)

            name
0      Customers
1     OrderItems
2         Orders
3       Payments
4       Products
5  sales_summary
6    sales_table
7   sales_table1

In [3]:
tables_to_check = [
    "Customers",
    "Orders",
    "OrderItems",
    "Payments",
    "Products",
    "sales_table",
    "sales_table1",
    "sales_summary"
]

for table in tables_to_check:
    count = pd.read_sql_query(
        f'SELECT COUNT(*) AS row_count FROM "{table}"',
        conn
    ).iloc[0, 0]

    print(f"{table}: {count:,} rows")

Customers: 89,316 rows
Orders: 89,316 rows
OrderItems: 89,316 rows
Payments: 89,316 rows
Products: 27,451 rows
sales_table: 28,607 rows
sales_table1: 28,607 rows
sales_summary: 28,607 rows

In [4]:
for table in ["Orders", "Customers", "OrderItems", "Payments", "Products"]:
    print(f"\n--- {table} ---")
    display(pd.read_sql_query(
        f'PRAGMA table_info("{table}")',
        conn
    )[["name", "type"]])

--- Orders ---

                            name  type
0                       order_id  TEXT
1                    customer_id  TEXT
2                   order_status  TEXT
3       order_purchase_timestamp  TEXT
4              order_approved_at  TEXT
5      order_delivered_timestamp  TEXT
6  order_estimated_delivery_date  TEXT

--- Customers ---

                       name    type
0               customer_id    TEXT
1  customer_zip_code_prefix  BIGINT
2             customer_city    TEXT
3            customer_state    TEXT

--- OrderItems ---

               name   type
0          order_id   TEXT
1        product_id   TEXT
2         seller_id   TEXT
3             price  FLOAT
4  shipping_charges  FLOAT
5              cost   REAL

--- Payments ---

                   name    type
0              order_id    TEXT
1    payment_sequential  BIGINT
2          payment_type    TEXT
3  payment_installments  BIGINT
4         payment_value   FLOAT

--- Products ---

                    name  type
0             product_id  TEXT
1  product_category_name  TEXT
2       product_weight_g  REAL
3      product_length_cm  REAL
4      product_height_cm  REAL
5       product_width_cm  REAL